
name: practice-cl-cd
on:
    push:
      branches:
        -main

jobs:
  test:
    runs-on: mac-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - run: 
          npm install
          npx run test

            